### ISSUE TITLE
User Interface issue?

### ISSUE THREAD

**Issue by theRFnoob** [DSpotDevelopers/makerdao-psm#6]
Hello,

the UI of the website https://ipfs.io/ipfs/QmY9WUjD3YYfyzmegDYxE8yZFcNT3L9TRQSGCJQaWjXxwk/
seems to have a problem when we try to swap DAI for USDC.

The UI shows 0.1% fees but it should be 0.04%. 
The numerical calculations are correct (they use 0.04% indeed).

<img width="763" alt="Screenshot 2021-04-11 at 22 48 09" src="https://user-images.githubusercontent.com/66557887/114320798-fdd3c780-9b17-11eb-8b5b-52c1ab9906e2.png">

**Comment by DiegoAWS** [comment]
Already solved in a previews version
